apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xro6yyvlu-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:654ce8fc88d94574d89f3fdd5021b84ea9771582@sha256:ca31ff1541d73ab318242c77f11a6671aaab737529c0e31889bb60a6bbdb5280
          name: container-image
